apiVersion: v1
kind: Service
metadata:
  name: node-lightweight-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: node-lightweight-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
